apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.AppName }}-service
  namespace: {{ .Values.NameSpace }}
spec:
  ports:
  - port: 9093
    targetPort: 9093
  selector:
    app: {{ .Values.AppName }}