AppName: mlflow
Namespace: sake

mlflow:
  image: killiankopp/mlflow:v2.17.0-psycopg2
  artifactRoot: "gs://sake-mlflow-storage"

postgre:
  hostname: mlflow-postgres
  port: 5432
  username: mlflow
  database: mlflowdb

gcp:
  secretName: sake-gcp-secret
  serviceAccountKey: service-account-key.json

service:
  type: ClusterIP
  port: 5000