apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.AppName }}-service
  namespace: {{ .Values.NameSpace }}
spec:
  ports:
  - port: 80
    targetPort: 8901
  selector:
    app: {{ .Values.AppName }}