apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.AppName }}
  namespace: {{ .Values.NameSpace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.AppName }}
  template:
    metadata:
      labels:
        app: {{ .Values.AppName }}
    spec:
      containers:
      - name: {{ .Values.AppName }}
        image: {{ .Values.DockerImage }}
        ports:
        - containerPort: 80
        env:
        - name: ENDPOINT_URL_OCR
          value: {{ .Values.ENDPOINT_URL_OCR }}
        - name: ENDPOINT_URL_CLEAN
          value: {{ .Values.ENDPOINT_URL_CLEAN }}