apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.AppName }}
  namespace: {{ .Values.NameSpace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.AppName }}
  template:
    metadata:
      labels:
        app: {{ .Values.AppName }}
    spec:
      securityContext:
        sysctls:
          - name: fs.inotify.max_user_instances
            value: "1024"
          - name: fs.inotify.max_user_watches
            value: "524288"
      containers:
      - name: {{ .Values.AppName }}
        image: {{ .Values.DockerImage }}
        ports:
        - containerPort: 80
        env:
        - name: URL_BACKEND
          value: "{{ .Values.URL_BACKEND }}"
        envFrom:
          - secretRef:
              name: aws-secrets