apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.AppName }}
  namespace: {{ .Values.NameSpace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.AppName }}
  template:
    metadata:
      labels:
        app: {{ .Values.AppName }}
    spec:
      containers:
      - name: {{ .Values.AppName }}
        image: {{ .Values.DockerImage }}
        ports:
        - containerPort: 80
        env:
        - name: URL_BACKEND
          value: "{{ .Values.URL_BACKEND }}"
        - name: KEYCLOAK_SERVER_URL
          value: "{{ .Values.KEYCLOAK_SERVER_URL }}"
        - name: KEYCLOAK_REALM_NAME
          value: "{{ .Values.KEYCLOAK_REALM_NAME }}"
        - name: KEYCLOAK_CLIENT_ID
          value: "{{ .Values.KEYCLOAK_CLIENT_ID }}"
        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: keycloak-secrets
              key: KEYCLOAK_CLIENT_SECRET
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_BUCKET_NAME