apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mlflow
  namespace: {{ .Values.Namespace }}
  labels:
    app: {{ .Values.AppName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.AppName }}
  template:
    metadata:
      labels:
        app: {{ .Values.AppName }}
    spec:
      containers:
        - name: {{ .Values.AppName }}
          image: {{ .Values.mlflow.image }}
          command: ["sh", "-c"]
          args:
            - "mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri postgresql://{{ .Values.postgre.username }}:${POSTGRES_PASSWORD}@{{ .Values.postgre.hostname }}.{{ .Values.Namespace }}.svc.cluster.local:{{ .Values.postgre.port }}/{{ .Values.postgre.database }} --default-artifact-root ${ARTIFACT_ROOT}"
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mlflow-postgres-secret
                  key: postgres-password
            - name: ARTIFACT_ROOT
              value: {{ .Values.mlflow.artifactRoot }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/gcp/service-account-key.json  
          volumeMounts:
            - name: gcp-credentials
              mountPath: /var/secrets/gcp  
              readOnly: true
          ports:
            - containerPort: {{ .Values.service.port }}
      volumes:
        - name: gcp-credentials
          secret:
            secretName: {{ .Values.gcp.secretName }}  